version: '3.9'


services:
  app:
    build: .
    container_name: app
    depends_on:
      - db_in

    ports:
      - 8000:8000

  db_in:
    image: postgres

    env_file:
      - .env
    container_name: db
    ports:
      - 5432:5432    

